### ISSUE TITLE
How do I adjust the panel divider size and color

### ISSUE THREAD

**Issue by kendoori** [benji300/joplin-favorites#10]
I have moved the Favorites to the left, and changed the background and font color to match the default notebooks/tags panel. Somehow this has created a thick divider between the Favorites.

![Selection_212](https://user-images.githubusercontent.com/2447420/123658259-8a308500-d7ff-11eb-8497-7048242a2120.png)

**Comment by benji300** [comment]
Unfortunately this is nothing which is caused by the plugin. It is the Apps default behavior. Which places between each panel an empty white space (splitter) for resizing the panel widths and heights. 
In the "Change application layout" view you can see where these splitters are added by the app.

![image](https://user-images.githubusercontent.com/54955848/124425486-e730bb80-dd68-11eb-832c-eed70576480b.png)

You could only try to change the background color of this splitter by with custom css.

**Comment by benji300** [comment]
As a workaround the following code could be pasted into `userchrome.css`:
```css
/* remove white border (~5px, right) from columns with one panel */
.rli-root > .resizableLayoutItem > div {
  width: 100% !important;
}
/* remove white border (~5px, right, below) from columns with two or more panels */
.rli-root > .resizableLayoutItem > .resizableLayoutItem > div {
  height: 100% !important;
  width: 100% !important;
}
/* remove small border (1px, below) plugin iframes */
div.resizableLayoutItem iframe {
  border-bottom: none !important;
}
```

**Comment by lohau** [comment]
That got rid of the dividers, but now the favorites panel is only half as wide as the notebook panel:
![Bildschirmfoto von 2023-04-07 10-06-36](https://user-images.githubusercontent.com/130137200/230569423-ff60502c-edc7-4160-9be8-789bc331810e.png)

**Comment by mygithubdevaccount** [comment]
> That got rid of the dividers, but now the favorites panel is only half as wide as the notebook panel: 

Just remove `width: 100% !important;` in the second rule to be:

```css
.rli-root > .resizableLayoutItem > .resizableLayoutItem > div {
  height: 100% !important;
}
```
